[project]
name = "topology"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "emoji>=2.15.0",
    "graphable",
    "rich>=14.2.0",
]

[tool.uv.workspace]
members = [
    "graphable",
]

[tool.uv.sources]
graphable = { workspace = true }

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.14.11",
    "ty>=0.0.11",
]
